### PR TITLE
Add Dark Mode

### PR DESCRIPTION
**Pull request by Muz4mmil**

### CODE REVIEW

**Comment by OmkarKirpan** [comment]
Hi @Muz4mmil 
Changes looks good 👍🏻 😊 
Also could you please add test case for dark mode button?

**Comment by Muz4mmil** [comment]
> Hi @Muz4mmil 
> Changes looks good 👍🏻 😊 
> Also could you please add test case for dark mode button?

Sorry, I don't know how to write test-cases for CSS

**Comment by OmkarKirpan** [comment]
@Muz4mmil it's ok, we can add it later

**Review by OmkarKirpan — APPROVED** [review]
Looks good to me 👍🏻

**Comment by OmkarKirpan** [comment]
resolves #14

**Pull request merged**
